// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthMode } from "../AuthMode";
import type { PlanType } from "../PlanType";

export type AccountProfile = { id: string, alias: string, authMode: AuthMode, email: string | null, planType: PlanType | null, enabled: boolean,
/**
 * Whether this profile currently has locally managed credentials.
 * Credential values are never returned.
 */
authenticated: boolean, priority: number, createdAt: bigint, lastUsedAt: bigint | null, note: string | null, isDefault: boolean, isActive: boolean, };
