// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountAutoSelectionPolicy } from "./AccountAutoSelectionPolicy";
import type { AccountPriorityOrder } from "./AccountPriorityOrder";

export type AccountAutoSelection = { enabled: boolean, policy: AccountAutoSelectionPolicy, priorityOrder: AccountPriorityOrder, };
