// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AccountProfileLogin = { "type": "apiKey", } | { "type": "chatgpt", loginId: string, authUrl: string, } | { "type": "chatgptDeviceCode", loginId: string, verificationUrl: string, userCode: string, } | { "type": "amazonBedrock", };
