// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EventWakeScope = { "type": "thread" } | { "type": "subscription", subscriptionId: string, } | { "type": "projectDelivery", projectId: string, target: string, } | { "type": "projectReview", projectId: string, };
