// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EventSubscriptionFilter = { source: string, eventTypes: Array<string>, labels: { [key in string]?: string }, };
