// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventWakePolicy } from "./EventWakePolicy";
import type { EventWakeScope } from "./EventWakeScope";

export type EventWakePolicyEntry = { scope: EventWakeScope, policy: EventWakePolicy, suspended: boolean, authorizationRef: string, };
