// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventSourceCursor } from "./EventSourceCursor";
import type { EventSubscriptionFilter } from "./EventSubscriptionFilter";

export type EventSubscription = { id: string, threadId: string, filter: EventSubscriptionFilter | null, sourceCursor: EventSourceCursor | null, heartbeatIntervalSeconds: number | null, nextHeartbeatAt: bigint | null, createdAt: bigint, updatedAt: bigint, };
