// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventWakePolicy } from "./EventWakePolicy";
import type { EventWakeScope } from "./EventWakeScope";

export type EventWakePolicyCommand = { "action": "read" } | { "action": "set", scope: EventWakeScope, policy: EventWakePolicy, expectedRevision: number, authorizationRef: string, };
