// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventSourceCursor } from "./EventSourceCursor";

/**
 * Security boundary from `security-assumptions.md`: only these bounded metadata fields cross
 * ingress; unknown publisher payload fields are rejected rather than retained or injected.
 */
export type IngressEvent = { id: string, source: string, eventType: string, cursor: EventSourceCursor, labels: { [key in string]?: string },
/**
 * Event occurrence time as whole Unix seconds.
 */
occurredAt: bigint, };
