// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LocalUsageActivityKind = "requirements" | "specification" | "repositoryAnalysis" | "research" | "diagnosis" | "architectureDesign" | "workPlanning" | "coding" | "configuration" | "refactoring" | "dependencyOrBuildChange" | "testAuthoring" | "documentationAuthoring" | "dataOrSchemaChange" | "buildValidation" | "unitTesting" | "integrationTesting" | "browserQa" | "compatibilityTesting" | "migrationRehearsal" | "verificationReview" | "packaging" | "deployment" | "rollback" | "runtimeOperations" | "monitoring" | "userElaboration" | "statusUpdate" | "completionHandoff" | "reviewFeedback" | "coordination" | "accountingOverhead" | "mixed" | "unknown";
