// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalUsageCoverage } from "./LocalUsageCoverage";
import type { LocalUsageProvenance } from "./LocalUsageProvenance";

export type LocalUsageTokenCategory = { categoryKey: string, count: bigint | null, provenance: LocalUsageProvenance, coverage: LocalUsageCoverage, };
