// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalUsageAggregate } from "./LocalUsageAggregate";

export type LocalUsageRepository = { repositoryKey: string, label: string, createdAt: bigint, updatedAt: bigint, aggregate: LocalUsageAggregate, };
