// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalUsageCoverage } from "./LocalUsageCoverage";

export type LocalUsageAggregate = { inputTokens: bigint | null, cachedInputTokens: bigint | null, cacheWriteInputTokens: bigint | null, outputTokens: bigint | null, reasoningOutputTokens: bigint | null, totalTokens: bigint | null, modelRequests: bigint, toolCalls: bigint, durationMs: bigint, coverage: LocalUsageCoverage, };
