// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalUsageReportActivityTokenAggregate } from "./LocalUsageReportActivityTokenAggregate";
import type { LocalUsageReportClassificationCount } from "./LocalUsageReportClassificationCount";
import type { LocalUsageReportCounts } from "./LocalUsageReportCounts";
import type { LocalUsageReportCoverage } from "./LocalUsageReportCoverage";
import type { LocalUsageReportFormulas } from "./LocalUsageReportFormulas";
import type { LocalUsageReportRepositoryParticipation } from "./LocalUsageReportRepositoryParticipation";
import type { LocalUsageReportScope } from "./LocalUsageReportScope";
import type { LocalUsageReportTimeMetrics } from "./LocalUsageReportTimeMetrics";
import type { LocalUsageReportTimeRange } from "./LocalUsageReportTimeRange";
import type { LocalUsageReportTokenAggregate } from "./LocalUsageReportTokenAggregate";
import type { LocalUsageReportToolMetrics } from "./LocalUsageReportToolMetrics";

/**
 * Versioned, full-fidelity local usage report.
 *
 * The report preserves provider-native token categories and keeps coverage,
 * measurement, attribution, and timing facts separate so clients do not need
 * to infer unsupported totals.
 */
export type LocalUsageReport = { schemaVersion: number, kind: string, databaseSchemaVersion: bigint, taxonomyVersion: bigint, scope: LocalUsageReportScope, account: string | null, timeRange: LocalUsageReportTimeRange | null, coverage: LocalUsageReportCoverage, counts: LocalUsageReportCounts, providerTokens: Array<LocalUsageReportTokenAggregate>, providerTokensByActivity: Array<LocalUsageReportActivityTokenAggregate>, tools: LocalUsageReportToolMetrics, time: LocalUsageReportTimeMetrics, classifications: Array<LocalUsageReportClassificationCount>, repositoryParticipation: LocalUsageReportRepositoryParticipation, formulas: LocalUsageReportFormulas, };
