// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalUsageCoverage } from "./LocalUsageCoverage";
import type { LocalUsageEventKind } from "./LocalUsageEventKind";
import type { LocalUsageProvenance } from "./LocalUsageProvenance";

export type LocalUsageEvent = { eventId: string, threadId: string | null, repositoryKey: string | null, occurredAt: bigint, kind: LocalUsageEventKind, provenance: LocalUsageProvenance, coverage: LocalUsageCoverage, };
