// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalUsageActivityKind } from "./LocalUsageActivityKind";
import type { LocalUsageActivityState } from "./LocalUsageActivityState";
import type { LocalUsagePhase } from "./LocalUsagePhase";
import type { LocalUsageProvenance } from "./LocalUsageProvenance";

export type LocalUsageActivity = { activityId: string, threadId: string, agentId: string, phase: LocalUsagePhase, activity: LocalUsageActivityKind, state: LocalUsageActivityState, startedAt: bigint, endedAt: bigint | null, provenance: LocalUsageProvenance, };
