// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalUsageAggregate } from "./LocalUsageAggregate";

export type LocalUsageThread = { threadId: string, repositoryKeys: Array<string>, accountId: string | null, startedAt: bigint, updatedAt: bigint, aggregate: LocalUsageAggregate, };
