// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LocalUsageReportTokenAggregate = { category: string, repositoryBucket: string,
/**
 * Safe display label resolved at read time. Machine clients can continue
 * to use `repository_bucket` as the stable privacy-preserving key.
 */
repositoryLabel: string | null, measurementProvenance: string, measuredTokens: bigint, exactTokens: bigint | null, unknownObservations: bigint, observationCount: bigint, };
