// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LocalUsageReportActivityTokenAggregate = { phase: string, activity: string, attributionProvenance: string, measuredTokens: bigint, exactTokens: bigint | null, unknownObservations: bigint, };
