// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalUsageReportDuration } from "./LocalUsageReportDuration";
import type { LocalUsageReportToolOutcome } from "./LocalUsageReportToolOutcome";

export type LocalUsageReportToolMetrics = { count: bigint, duration: LocalUsageReportDuration, durationBasis: string, outcomes: Array<LocalUsageReportToolOutcome>, };
