// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalUsageProvenance } from "./LocalUsageProvenance";
import type { LocalUsageToolStatus } from "./LocalUsageToolStatus";

export type LocalUsageTool = { toolCallId: string, threadId: string, repositoryKey: string | null, toolName: string, operationFamily: string, startedAt: bigint, completedAt: bigint | null, status: LocalUsageToolStatus, provenance: LocalUsageProvenance, };
