// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A versioned standard API-equivalent estimate, not an invoice or subscription charge.
 * Missing observations and unpriced models remain explicit in status and counts.
 */
export type LocalUsageReportCost = { basis: string, currency: string, status: string, processingTier: string, estimatedUsdMicros: bigint | null, inputUsdMicros: bigint | null, cachedInputUsdMicros: bigint | null, cacheWriteUsdMicros: bigint | null, outputUsdMicros: bigint | null, inputTokens: bigint, uncachedInputTokens: bigint, cachedInputTokens: bigint, cacheWriteTokens: bigint, outputTokens: bigint, reasoningTokens: bigint, providerTotalTokens: bigint, pricedObservations: bigint, unknownObservations: bigint, rateCardRefs: Array<string>, };
