// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectAutomationJob } from "./ProjectAutomationJob";
import type { ProjectAutomationMode } from "./ProjectAutomationMode";
import type { ProjectDeliveryObligation } from "./ProjectDeliveryObligation";
import type { ProjectWorkPurpose } from "./ProjectWorkPurpose";

export type ProjectAutomation = { projectId: string, ownerThreadId: string, revision: number, mode: ProjectAutomationMode, startedAtMs: number, lastActivityAtMs: number, reviewWindowStartMs: number, nextReviewAtMs: number, reviewIntervalMs: number, paused: boolean, threads: { [key in string]?: ProjectWorkPurpose }, completed: boolean, threadWorkstreams: { [key in string]?: string }, threadOutcomes: { [key in string]?: string }, threadExperiments: { [key in string]?: string }, delivery: { [key in string]?: ProjectDeliveryObligation }, review: ProjectAutomationJob | null, lastReviewRef: string | null, };
