// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectAutomation } from "./ProjectAutomation";
import type { ProjectAutomationCapability } from "./ProjectAutomationCapability";

export type ProjectAutomationCommandResponse = { capability: ProjectAutomationCapability | null, project: ProjectAutomation | null, };
