// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectAutomationJobKind } from "./ProjectAutomationJobKind";

export type ProjectAutomationJob = { id: string, kind: ProjectAutomationJobKind, dueAtMs: number, revision: number, notified: boolean, decisionRef: string | null, };
