// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectAutomationJob } from "./ProjectAutomationJob";

export type ProjectDeliveryObligation = { target: string, workstream: string, surface: string, acceptance: string, startedAtMs: number, deliveredAtMs: number | null, deliveryIntervalMs: number, hardStopIntervalMs: number, deliveryDueAtMs: number, hardStopAtMs: number, revision: number, paused: boolean, job: ProjectAutomationJob | null, evidenceRef: string | null, };
