// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectAutomationCommand } from "./ProjectAutomationCommand";

export type ProjectAutomationCommandParams = { projectId?: string | null, threadId?: string | null, expectedRevision?: number | null, command?: ProjectAutomationCommand | null, };
