pub mod auth;
pub mod auth_env_telemetry;
pub mod test_support;
pub mod token_data;

mod callback_params;
mod device_code_auth;
mod outbound_proxy;
mod pkce;
mod server;
mod success_page;

pub use callback_params::LoginCallbackResult;
pub use callback_params::LoginOnboardingEntrypoint;
pub use codex_config::types::AuthCredentialsStoreMode;
pub use codex_http_client::BuildCustomCaTransportError as BuildLoginHttpClientError;
pub use device_code_auth::DeviceCode;
pub use device_code_auth::complete_device_code_login;
pub use device_code_auth::request_device_code;
pub use device_code_auth::run_device_code_login;
pub use server::LoginServer;
pub use server::ServerOptions;
pub use server::ShutdownHandle;
pub use server::run_login_server;
pub use success_page::CODEX_OPEN_APP_URL;
pub use success_page::LoginSuccessPage;
pub use success_page::LoginSuccessPageBrand;

pub use auth::AccountLease;
pub use auth::AccountManagementError;
pub use auth::AgentIdentityAuthPolicy;
pub use auth::AuthConfig;
pub use auth::AuthDotJson;
pub use auth::AuthFileCleanupError;
pub use auth::AuthFileDurabilityError;
pub use auth::AuthHeaders;
pub use auth::AuthKeyringBackendKind;
pub use auth::AuthManager;
pub use auth::AuthManagerConfig;
pub use auth::AuthManagerInitializationError;
pub use auth::AuthManagerLease;
pub use auth::AuthProfileMetadata;
pub use auth::CLIENT_ID;
pub use auth::CLIENT_ID_OVERRIDE_ENV_VAR;
pub use auth::CODEX_ACCESS_TOKEN_ENV_VAR;
pub use auth::CODEX_API_KEY_ENV_VAR;
pub use auth::CodexAuth;
pub use auth::ExternalAuth;
pub use auth::ExternalAuthConflictSource;
pub use auth::ExternalAuthFuture;
pub use auth::ExternalAuthRefreshContext;
pub use auth::ExternalAuthRefreshReason;
pub use auth::LegacyAuthMigrationError;
pub use auth::LegacyAuthMigrationOutcome;
pub use auth::ManagedAccountPriorityMutation;
pub use auth::ManagedAccountSnapshot;
pub use auth::ManagedAccountSummary;
pub use auth::OPENAI_API_KEY_ENV_VAR;
pub use auth::PendingProfileLogin;
pub use auth::PendingProfileLoginError;
pub use auth::ProfileAuthCommitError;
pub use auth::ProfileAuthRouter;
pub use auth::ProfileAuthRouterConfig;
pub use auth::ProfileAuthRouterError;
pub use auth::ProfileAuthStorage;
pub use auth::ProfileRemovalOutcome;
pub use auth::REFRESH_TOKEN_URL_OVERRIDE_ENV_VAR;
pub use auth::REVOKE_TOKEN_URL_OVERRIDE_ENV_VAR;
pub use auth::RefreshTokenError;
pub use auth::RouterExternalAuthState;
pub use auth::SharedProfileAuthRouter;
pub use auth::UnauthorizedRecovery;
pub use auth::default_client;
pub use auth::enforce_login_restrictions;
pub use auth::is_workload_identity_selected;
pub use auth::load_auth_dot_json;
pub use auth::login_with_access_token;
pub use auth::login_with_access_token_to_profile;
pub use auth::login_with_api_key;
pub use auth::login_with_api_key_to_profile;
pub use auth::login_with_bedrock_access_keys;
pub use auth::login_with_bedrock_access_keys_to_profile;
pub use auth::login_with_bedrock_api_key;
pub use auth::login_with_bedrock_api_key_to_profile;
pub use auth::logout;
pub use auth::logout_profile_with_revoke;
pub use auth::logout_with_revoke;
pub use auth::migrate_legacy_auth_if_needed;
pub use auth::oauth_client_id;
pub use auth::read_codex_access_token_from_env;
pub use auth::read_managed_accounts;
pub use auth::read_openai_api_key_from_env;
pub use auth::save_auth;
pub use auth::set_all_managed_account_priorities;
pub use auth::set_managed_account_priority;
pub use auth_env_telemetry::AuthEnvTelemetry;
pub use auth_env_telemetry::collect_auth_env_telemetry;
pub use outbound_proxy::AuthRouteConfig;
pub use token_data::TokenData;
