// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "./AbsolutePathBuf";
import type { LocalUsageAccountingCapability } from "./v2/LocalUsageAccountingCapability";
import type { MultiAccountCapability } from "./v2/MultiAccountCapability";

export type InitializeResponse = { userAgent: string,
/**
 * Absolute path to the server's $CODEX_HOME directory.
 */
codexHome: AbsolutePathBuf,
/**
 * Platform family for the running app-server target, for example
 * `"unix"` or `"windows"`.
 */
platformFamily: string,
/**
 * Operating system for the running app-server target, for example
 * `"macos"`, `"linux"`, or `"windows"`.
 */
platformOs: string,
/**
 * Advertises the additive multi-account profile extension.
 */
multiAccount: MultiAccountCapability | null,
/**
 * Advertises the additive local usage-accounting extension.
 */
localUsageAccounting: LocalUsageAccountingCapability | null, };
